baseURL: https://about.gameontext.org/
disableLiveReload: true
enableGitInfo: true
googleAnalytics: UA-90113653-2
languageCode: en-us
markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: false
    style: monokai-light
    tabWidth: 2
title: "Game On! Hands-on adventures in cloud native development."
taxonomies:
  tag: tags
