# Use the same image we use to build/run locally to test branches & PRs
sudo: required

language: generic

services:
  - docker

env:
  global:
  - DOCKER_COMPOSE_VERSION: 1.14.0
  - ENCRYPTION_LABEL: 752dfc0eab06

before_install:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ] || [ "$TRAVIS_BRANCH" != "master" ]; then
      bash <(curl -s https://raw.githubusercontent.com/gameontext/gameon/master/build/updateTravisDocker.sh);
      docker-compose pull;
    fi'

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ] || [ "$TRAVIS_BRANCH" != "master" ]; then
      mkdir -p _site;
      docker-compose run -e PAGES_REPO_NWO site jekyll b --verbose;
      docker-compose run site htmlproofer --assume-extension ./_site;
    fi'
  - 'if [ "$TRAVIS_EVENT_TYPE" == "cron" ]; then
      ./today.sh;
    fi'
