# Use the same image we use to build/run locally to build static content.
sudo: required

language: generic

services:
  - docker

env:
  global:
  - DOCKER_COMPOSE_VERSION: 1.14.0
  - ENCRYPTION_LABEL: 752dfc0eab06

before_install:
  - bash <(curl -s https://raw.githubusercontent.com/gameontext/gameon/master/images/updateTravisDocker.sh)
  - docker-compose pull
  - mkdir publish

script:
  - docker-compose run -e PAGES_REPO_NWO site jekyll b --verbose
    && sudo chown -R travis:travis .
    && (docker-compose run site htmlproofer --assume-extension ./_site || true)


after_success:
  - ./deploy.sh
