version: '2'

services:
  site:
    command: jekyll serve  --verbose --drafts --future --watch --incremental --host 0.0.0.0
    image: jekyll/jekyll:latest
    volumes:
      - $PWD:/srv/jekyll
      - $PWD/vendor/bundle:/usr/local/bundle
    ports:
      - 35729:35729
      - 3000:3000
      - 8000:4000
    environment:
      - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    container_name: go-blog
