version: '2'

services:
  jekyll:
    image: jekyll/builder:pages
    command: [sh, -c, "ls /srv/jekyll/vendor; if [ ! -f '/srv/jekyll/vendor/done' ]; then bundle update && touch /srv/jekyll/vendor/done; fi"]
    volumes:
      - $PWD:/srv/jekyll
      - $PWD/.vendor:/srv/jekyll/vendor
    container_name: jekyll
    environment:
      - BUNDLE_CACHE

  go-blog:
    build: .
    command: [sh, -c, "while [ ! -f '/srv/jekyll/vendor/done' ]; do echo 'waiting for update...'; sleep 2; done; bundle exec jekyll s --verbose --drafts --future --watch --incremental --host=0.0.0.0"]
    depends_on:
      - jekyll
    volumes:
      - $PWD:/srv/jekyll
      - $PWD/.vendor:/srv/jekyll/vendor
    ports:
      - "8000:4000"
      - "35729:35729"
    container_name: go-blog
    environment:
      - POLLING
      - BUNDLE_CACHE
      - PAGES_REPO_NWO=gameontext/gameontext.github.io
