baseURL: ""
uglyURLs: true
disableLiveReload: true
enableGitInfo: true
googleAnalytics: UA-90113653-2
languageCode: en-us
frontmatter:
  date:
    - ":filename"
    - ":git"
    - ":default"
permalinks:
  posts: /:year/:month/:day/:slug
markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: false
    style: monokai-light
    tabWidth: 2
title: "Game On! Adventures with microservices"
params:
  description: "Hands-on experiment building microservices and cloud native applications"
taxonomies:
  tag: tags
publishDir: "../public"
security:
  enableInlineShortcodes: false
  exec:
    allow:
    - ^(dart-)?sass(-embedded)?$
    - ^go$
    - ^npx$
    - ^postcss$
    - ^asciidoctor$
    osEnv:
    - (?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+|(XDG_CONFIG_)?HOME|USERPROFILE|SSH_AUTH_SOCK|DISPLAY|LANG)$
  funcs:
    getenv:
    - ^HUGO_
    - ^CI$
  goTemplates:
    allowActionJSTmpl: false
  http:
    mediaTypes: null
    methods:
    - (?i)GET|POST
    urls:
    - .*